<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbPNAmrBrutoInput"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://www.ibm.com/maximo"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/IP-AMR-SOA-QA/PNAmrBruto/dbPNAmrBrutoInput"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mxws="http://www.ibm.com/maximo/wsdl/IPPN_METER">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/dbPNAmrBrutoInput.wsdl"/>
        <oracle-xsl-mapper:rootElement name="AmrBrutoCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbPNAmrBrutoInput"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="http://192.168.100.196/meaweb/wsdl/IPPN_METER.wsdl"/>
        <oracle-xsl-mapper:rootElement name="QueryIPPN_METER" namespace="http://www.ibm.com/maximo"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAY 31 11:05:02 ICT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:QueryIPPN_METER>
      <tns:IPPN_METERQuery>
        <tns:WHERE>
          <xsl:value-of select="concat (&quot;METERID = '&quot;, /ns0:AmrBrutoCollection/ns0:AmrBruto/ns0:meterid, &quot;'&quot; )"/>
        </tns:WHERE>
      </tns:IPPN_METERQuery>
    </tns:QueryIPPN_METER>
  </xsl:template>
</xsl:stylesheet>
