<wsdl:definitions
     name="dbUpdatePNAmrBruto"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IP-AMR-SOA-QA/PNAmrBruto/dbUpdatePNAmrBruto"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IP-AMR-SOA-QA/PNAmrBruto/dbUpdatePNAmrBruto"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbUpdatePNAmrBruto"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbUpdatePNAmrBruto_plt" >
    <plt:role name="dbUpdatePNAmrBruto_role" >
      <plt:portType name="tns:dbUpdatePNAmrBruto_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbUpdatePNAmrBruto" schemaLocation="../Schemas/dbUpdatePNAmrBruto_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="AmrBrutoCollection_msg">
        <wsdl:part name="AmrBrutoCollection" element="top:AmrBrutoCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbUpdatePNAmrBruto_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:AmrBrutoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
