<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="dbPNAmrPemakaianSendiriInput"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IP-AMR-SOA/PNAmrPemakaianSendiri/dbPNAmrPemakaianSendiriInput"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IP-AMR-SOA/PNAmrPemakaianSendiri/dbPNAmrPemakaianSendiriInput"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbPNAmrPemakaianSendiriInput"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://ebs.indonesiapower.co.id/schema/fault"
    >
    <plt:partnerLinkType name="dbPNAmrPemakaianSendiriInput_plt">
        <plt:role name="dbPNAmrPemakaianSendiriInput_role">
            <plt:portType name="tns:dbPNAmrPemakaianSendiriInput_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbPNAmrPemakaianSendiriInput"
                 schemaLocation="../Schemas/dbPNAmrPemakaianSendiriInput_table.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://ebs.indonesiapower.co.id/schema/fault" schemaLocation="../Schemas/fault.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="AmrPsCollection_msg">
        <wsdl:part name="AmrPsCollection" element="top:AmrPsCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbPNAmrPemakaianSendiriInput_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:AmrPsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
