<wsdl:definitions
     name="dbUpdatePNAmrNetto"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IP-AMR-SOA/PNAmrNetto/dbUpdatePNAmrNetto"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IP-AMR-SOA/PNAmrNetto/dbUpdatePNAmrNetto"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbUpdatePNAmrNetto"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbUpdatePNAmrNetto_plt" >
    <plt:role name="dbUpdatePNAmrNetto_role" >
      <plt:portType name="tns:dbUpdatePNAmrNetto_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbUpdatePNAmrNetto" schemaLocation="../Schemas/dbUpdatePNAmrNetto_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="AmrNettoCollection_msg">
        <wsdl:part name="AmrNettoCollection" element="top:AmrNettoCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbUpdatePNAmrNetto_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:AmrNettoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
